### ISSUE TITLE
Reconnect Problem

### ISSUE THREAD

**Issue by Petros144** [jhud/hackwatch#1]
Hi,

I was trying your Code and if I reset the ESP, it looses the Phone and I have to Clear the Bond on the iPhone and make a Hard reset of the ESP to get reconnected, do you have this issue?

PS: can you make a Tutorial on how to patch the files that are needed ?

```
// You need to patch the BLE library with setServiceSolicitationData as shown in:
//https://github.com/nkolban/esp32-snippets/issues/430#issuecomment-391491904
```

anyway, realy good work done here!!!

**Comment by jhud** [comment]
Thanks! There is no storage of BLE state in my class yet - it's on my todo list. Re. nkolban's patch - instructions are all in the link in the source.

**Comment by jhud** [comment]
Note that the ANCS notifications code has been moved out of this project to its own standalone library at https://github.com/Smartphone-Companions/ESP32NotificationsLib 
Ths repo is based on the latest Espressif libraries, and the good improvements of other contributors to the ESP32 BLE code. It would be much better to just use that library directly.
